### PR TITLE
2.0.0 FireFox Port with other changes

### PR DESCRIPTION
**Pull request by cTheDragons**
This is the version completed for release for both chrome and firefox. 

There are no other changes outstanding.

### CODE REVIEW

**Comment by paglias** [comment]
this also includes the changes in https://github.com/HabitRPG/habitica-chat-extension/pull/35?

**Comment by cTheDragons** [comment]
Yes it does

**Comment by paglias** [comment]
@cTheDragons let me know when you think it's ready for release

**Comment by cTheDragons** [comment]
Will do @paglias. Thank your for your patience with this. 

We  added the link to the new profile code from Habitica as the feature closes #13 . Will get the testers to confirm tomorrow it all ok. Did you need anything else from us on this to confirm it working ok?

**Comment by paglias** [comment]
No worries, if testers confirm it's working I'll briefly test it and release it on Chrome, for Firefox it might take a bit more because we don't have any extension published there yet

**Comment by cTheDragons** [comment]
#37 is ready for review.

The following socialites have reported back that successful test  in the [Testing & Bug Squashing for Dragon Tools](https://habitica.com/groups/guild/d9a0ec1e-352b-4697-a5d5-fb45c98fb4a3)

The following senior socialites have confirm that is working and ready for release
+ @QuartzFox (Tier 7 Socialite, Artisan) for Chrome
+ @LtCabel (Tier 6 Socialite, Artisan) for Chrome
+ @aspiring_advocate (Tier 4 Artisan, Linguist) for Firefox
+ @ravenlune (Aspiring Socialite and Scribe) for Chrome

There are two confirmed issues outstanding with this release,
1. For Firefox, when opening new chat windows sometimes, it does not always scroll to the bottom. (This is easily overcome by just manually scrolling yourself).
1. The skills cast will hide users information in the party window. Not a large issue, as many users would know their party members details, or just click the avatar for the profile information.

Both these issues and future feature requests both @[coder-extreme](/coder-extreme) and myself are happy for this to be released as is. Future work can be performed by the next aspiring blacksmith /  fletcher / comrade. (What is the correct term for working on official Habitica extension?)

Thank you for your time with this.

**Comment by cTheDragons** [comment]
@weeWitch (Tier 7 Linguist, Socialite, Artisan) for Firefox also confirms it is ready to release.

**Comment by paglias** [comment]
@cTheDragons thanks a lot to you and everyone who worked on this! I've just published the Chrome update

**Comment by paglias** [comment]
There seems to be a problem with the Firefox extension, I can't load the zip file because it says it's damaged, Even creating a new one myself doesn't work, any idea?

**Comment by cTheDragons** [comment]
+ Go to addons (Ctrl-Shift-A)
+ Press settings icon in the top right and choose Press ''Debug Add-Ons'' 
+ Press ''Load Temporary Addon'' 
+ From the repo, select the habitica-chat-extension-firefox.zip file in the firefox folder. The folder will be something like `C:\Users\cTheDragons\Downloads\habitica-chat-extension\firefox`
+ Refresh your [Habitica website](http://www.habitica.com), to see the extension in your browser.

*You will need to do this each time you open Firefox*

**Comment by paglias** [comment]
@cTheDragons that worked thanks! It's available at https://addons.mozilla.org/it/firefox/addon/habitica-chat-client-v2 (had to call it v2 because the slug was already used)

**Comment by paglias** [comment]
@cTheDragons can you give me your uuid and that of anyone who worked on this? I'd be happy to award you a contributor tier

**Comment by cTheDragons** [comment]
@benjaminbhollon / @code-extreme who completed the majority of the code is fc6bd8d5-94a2-462b-ac7f-9b03bc446d45
Mine is bc10ec41-4213-4482-bbb8-558e3c3ea8d5 I mainly managed, reorganised and documented and did some quick bug fixes.

Did you want any testers?

**Comment by paglias** [comment]
@cTheDragons @cTheDragons sorry for the delay but I've added this to your Habitica profile! @benjaminbhollon welcome to tier 1! @cTheDragons Notated this in your contribution list

**Comment by Alys** [comment]
I've increased @benjaminbhollon's tier because for Comrade tiers it's typical for us to give more than one at once when a large amount of effort has been involved in creating the third-party tool.

**Comment by benjaminbhollon** [comment]
@paglias @Alys Thank you!

**Pull request merged**
