### PR TITLE
Fix noon and midnight times for 12 hour clock, issue #57

### PR DESCRIPTION
**Pull request by junewerner**
When set to a 12 hour time midnight was displayed as 0:00 am and noon was displayed as 12:00 am. I fixed the time parsing logic, now mid night is displayed as 12:00 am and noon is displayed as 12:00 pm. This resolves issues #57.

### CODE REVIEW

**Comment by Alys** [comment]
I've added a comment related to this PR in the issue: https://github.com/HabitRPG/habitica-chat-extension/issues/57#issuecomment-634998645
I thought it would be better added there rather than here so that we can keep the discussion of the preferred fix in one place.

@junewerner I'm sorry I didn't post there earlier!

**Comment by junewerner** [comment]
Alright, this should now be fixed up to now display "12:01 am" at midnight and "noon" at noon.

**Comment by paglias** [comment]
Thanks @junewerner for this and the other PR! I'll be happy to award a contribution tier on Habitica if you want, just send your username or uuid

**Comment by junewerner** [comment]
Sounds great! My uuid is 2c5b537e-7c0c-4ae8-834e-6caac46b6834

**Pull request merged**
