### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by juanj**
Update readme with new changes and bump version.

The version changed from 2.2.6 to 2.2.8 on the readme because the version of the Firefox extension was previously updated without updating the readme. Now all 3 versions (Chrome, Firefox and the readme) are in sync.

Regarding storing the Firefox extension as a zip, I think is better to create a [new release and upload the zip file there](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository).

Git is not designed to work with binary files, and keeping track of binary files makes the repository heavier to download and slow to work with.

This pull request depends on #64 #65 #66 #67 #69

### CODE REVIEW

**Comment by cTheDragons** [comment]
For the Firefox.zip files maybe we should use Git LFS?

**Comment by juanj** [comment]
Git LFS can work, but is intended for files that are part of a project (mostly assets). Files that even if they are binary, you want to keep track of the different versions. In this case the zip file is not part of the project but a function of it state. The zip file can be generated at any point with the current code. There is no reason to keep versions of it.

Releases are intended exactly for this case. You define a point on your code to mark as the release and have the option to upload the 'binary' for that specific point.

If the problem is that is not trivial to create the zip file in the correct way, maybe adding a 'build' script that users can use to generate the zip after cloning the repository may be a better option.

**Comment by paglias** [comment]
thanks @juanj ! I've merged all the PR, and sent the new versions to Chrome and Firefox for review, they'll be published as soon as that passes. Also thanks @cTheDragons for all the testing!

@juanj if you have an Habitica username I'll be happy to award a contribution tier for these

**Comment by juanj** [comment]
Great! Hope they get approved soon!

@paglias Did you consider adding a release as mentioned above?
My Habitica User-ID is `2cedef5a-666a-484b-bd97-726209679923`

@cTheDragons Thanks for all the testing! And thanks for organizing the challenge!

**Comment by paglias** [comment]
ah, I had forgotten about the release, here it is https://github.com/HabitRPG/habitica-chat-extension/releases/tag/v2.2.8

and welcome to the 3rd tier!

**Pull request merged**
