### PR TITLE
Share code base

### LINKED ISSUE #68: Use the same code base for multiple browsers
Right now the add-on uses two copies of the same code to support multiple browser (Chrome and Firefox). This feels really ineficient. Double the work for each feature/bug fix.

There must be a better way to handle this. I don't have much experience building browser add-ons but this is worth investigating.
Maybe share the same core JavaScript files and use different sets of Manifest/Platform dependent files when "compiling" the extension.

This may also open the door to support more browsers easily.

### PR DESCRIPTION
**Pull request by juanj**
Fixes #68 

The code for Firefox and Chrome was almost identical, the only differences were some fields on the manifest, and the use of the namespace `browser` instead of `chrome`

Conveniently Firefox also recognizes the namespace `chrome`, so the same code can be use for both.

There was one problem with the settings storage. For some reason Firefox always returns `undefined` when calling `chrome.storage.sync.get()`. This was solved by calling `chrome.storage.local.get()` instead. The difference between these two objects is that the data saved to `sync` is shared across all browsers instances where the user is logged in. I don't think this is something essential for this extension but if needed we can find a workaround for that.

### CODE REVIEW

**Comment by paglias** [comment]
thanks @juanj ! As with the other PRs I'm happy to merge it after someone gets a chance to test it

**Comment by juanj** [comment]
@cTheDragons Hey! Can you give it a try? 
Not much changed, so all should be working.
The principal thing to test is that the user preferences are kept between sessions.

Also want to point out thet when testing the extension there is no need to make a zip file.
For Chrome: https://superuser.com/a/247654
For Firefox https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by cTheDragons** [comment]
I'm a little flat out with work and..... pirating so I may be a week or so before I can  get to it. ok?

**Comment by juanj** [comment]
No worries! Take your time.

**Comment by cTheDragons** [comment]
Yes this seems to be working! 

Good to see it all one branch.

Thanks for your hard work on this.

**Comment by paglias** [comment]
Thanks @juanj , I'm merging the code, if you have an Habitica uuid I'll be happy to note it in your profile

**Comment by juanj** [comment]
Happy to see this merged!

My UUID is `2cedef5a-666a-484b-bd97-726209679923`

**Pull request merged**
