### PR TITLE
Fix bugs noted by @cTheDragons

### PR DESCRIPTION
**Pull request by benjaminbhollon**
I fixed the following bugs:

* Avatar images stopped working this morning

* Ctrl+Enter keystroke couldn't be used to send messages.

* habitica-markdown.js was minified. (Firefox said not to have minified files)

I've done some testing in Chrome and Firefox and it seems to work fine.

### CODE REVIEW

**Comment by paglias** [comment]
Sorry for the delay @benjaminbhollon , I had to merge https://github.com/HabitRPG/habitica-chat-extension/pull/50 first so that caused some conflicts, could you give them a look? thanks

**Comment by benjaminbhollon** [comment]
Yeah, I'll fix it. I noticed that the avatars stopped working again. There's got to be a more intuitive way to do this than making an update every month. Does anyone know how the data attribute is calculated? That would really be helpful.

**Comment by paglias** [comment]
Sorry @benjaminbhollon but I'm not very familiar with the code of the extension itself

**Comment by benjaminbhollon** [comment]
@paglias It's the code of the website I'm worried about. Whenever the website displays an avatar, it uses a data attribute to show the CSS file that it's an avatar. The problem is that this data attribute is periodically changing, causing me to have to make changes to the code of the extension to allow the avatars to show. It would be much easier if I could figure out how the website determines what the data attribute is and then just add that to the code.

**Comment by paglias** [comment]
@benjaminbhollon sorry, can you make an example of this

> Whenever the website displays an avatar, it uses a data attribute to show the CSS file that it's an avatar.

? Are you literally talking about a `data` html attribute? On which element?

**Comment by benjaminbhollon** [comment]
For example: `<span data-v-42e99447 class="weapon_special_nomadsScimitar"></span>`

The data-v-42e99447 attribute is used on all of the avatar items. The number after the data-v- changes periodically and I'm trying to figure out why.

**Comment by paglias** [comment]
Ah, that attribute is randomly generated by Vue to match the element with the CSS styles but there's no way to know when it'll change or the value it'll have

**Comment by Alys** [comment]
@paglias Would it be permitted for us to ask for Habitica's code to be modified to manually add another attribute to those tags that the extension can use? It would prevent the extension needing to be changed and resubmitted periodically. If that's okay, I could log an issue for it in the main repo.

**Comment by paglias** [comment]
Sure, we can add a new class to better identify the element

**Comment by benjaminbhollon** [comment]
Thanks, that would be great!

**Comment by paglias** [comment]
It would be useful if you could open an issue explain which elements need a new identifier

**Comment by Alys** [comment]
@benjaminbhollon I know I promised to create the issue in my previous comment here but I think I'm starting to get sick and I can't focus on anything that needs thought. :-/  Would you mind doing it? Sorry! You'd have a much better idea of which elements need a class anyway.
https://github.com/HabitRPG/habitica/ repo in case that's not obvious.

**Comment by benjaminbhollon** [comment]
@Alys Just created! Let me know if I left anything out.

**Comment by benjaminbhollon** [comment]
Okay, I'm going to redo this stuff with the changes that have been made since I did this PR.

**Comment by paglias** [comment]
@benjaminbhollon thanks! just ping me or Alys when it's ready and we'll give a look as soon as possible

**Pull request closed without merging**
