### PR TITLE
Fix avatar not loading bug and unminify jQuery

### PR DESCRIPTION
**Pull request by benjaminbhollon**
Fixes Issues #43 and #40.

### CODE REVIEW

**Comment by cTheDragons** [comment]
Hi! Appears I can't update the Readme.md without creating a new PR. Appears @benjaminbhollon requires to complete it but not sure which of their accounts I should use. Have asked to manually update the file as it not much.


*Text Added:*
```
### 2.2.3 
+ Fix avatar not loading bug 
+ unminify jQuery (requirement from Firefox)

### 2.2.2 (Missed) 
+ Attempt to use Browserify
```

**Comment by benjaminbhollon** [comment]
I updated it, sorry for forgetting about that!

**Comment by paglias** [comment]
This LGTM! I won't have time to publish a new version to the stores until mid august but I'll add this to my list

**Comment by paglias** [comment]
thanks @benjaminbhollon ! I'll be happy to award you a contribution tier if you have an Habitica username

**Comment by Alys** [comment]
@paglias : @benjaminbhollon is loverofbooks / d904bd62-da08-416b-a816-ba797c9ee265 (I checked it for an Aspiring Socialites post about this so I figured I might as well post it here too :smile:)

**Comment by paglias** [comment]
thanks @Alys 

notated towards your fourth tier @benjaminbhollon

**Pull request merged**
